ascart/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('codereview.urls')),
]

codereview/urls.py
from django.urls import path
from .views import fetch_repos, scan_repository, show_reports
from . import views

app_name = 'codereview'

urlpatterns = [
    path('', fetch_repos, name='fetch-repos'),
    path('scan_repository/', scan_repository, name='scan_repository'),
    path('reports/', show_reports, name='show-reports'),
    path('reports/<int:report_id>/download/', views.download_scan_report, name='download_scan_report'),

]

codereview/models.py
from django.db import models

class ScanReport(models.Model):
    repository_name = models.CharField(max_length=255)
    review = models.TextField()
    scanned_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.repository_name} - {self.scanned_at}"

codereview/views.py
import logging, requests, openai, base64, os
from django.shortcuts import render
from django.conf import settings
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from github import Github, GithubException
from .models import ScanReport
from django.http import HttpResponse
from .pdf_utils import generate_pdf
from django.http import Http404
import re, json

logger = logging.getLogger(__name__)

openai.api_key = settings.OPENAI_API_KEY

def fetch_repos(request):
    headers = {'Authorization': f'token {settings.GITHUB_TOKEN}'}
    org_url = f'https://api.github.com/orgs/{settings.GITHUB_ORG_NAME}/repos'

    try:
        response = requests.get(org_url, headers=headers)
        response.raise_for_status()
        repos = response.json()
        context = {'repositories': repos}
    except requests.exceptions.HTTPError as http_err:
        logger.error(f"HTTP error occurred: {http_err}") 
        context = {'error': str(http_err)}
    except Exception as err:
        logger.error(f"An error occurred: {err}")
        context = {'error': str(err)}

    return render(request, 'codereview/repos.html', context)

def fetch_files_recursive(repo, path):
    contents = repo.get_contents(path)
    file_list = []

    while contents:
        file_content = contents.pop(0)
        if file_content.type == "dir":
            contents.extend(repo.get_contents(file_content.path))
        else:
            file_list.append(file_content)

    return file_list

def fix_json_commas(json_str):
    try:

        pattern = re.compile(r'}(?!\s*,)(?!\s*])(?=\s*{)')

        fixed_json_str = re.sub(pattern, '},', json_str)

        return fixed_json_str

    except Exception as e:
        print(f"An error occurred: {e}")
        return json_str

@csrf_exempt
def scan_repository(request):
    if request.method == 'POST':
        repo_full_name = request.POST.get('repo_full_name')

        extensions_to_neglect = ['.md']

        g = Github(settings.GITHUB_TOKEN)

        try:
            repo = g.get_repo(repo_full_name)
            all_files = fetch_files_recursive(repo, "")

            reviews = []

            for file in all_files:

                file_extension = os.path.splitext(file.name)[1].lower()

                if file_extension in extensions_to_neglect:
                    continue

                content = base64.b64decode(file.content).decode('utf-8') if file.encoding == 'base64' else file.content

                json_example = '''
                {
                    "File Name": "test.php",
                    "Vulnerability Name": "Command Injection",
                    "Description": "The code uses user-supplied input in a call to the EditUser() function without proper validation, allowing for potential command injection attacks.",
                    "Severity": "High",
                    "Vulnerable Code Snippet": "EditUser(\'email\', $email);",
                    "Remediation": "Use prepared statements or input validation to prevent user-supplied input from being executed as a command."
                },
                '''

                new_prompt = f"""Act as a SAST tool. You have to analyze the below code from {file.path} and provide results for all the unique security vulnerabilities present in the code, in JSON format. The JSON format for these findings should contain: File Name, Vulnerability Name, Description, Severity, Vulnerable Code Snippet, and Remediation.
                
                Make sure to perform the below mentioned 3 modifications when creating the JSON response:

                1. Change/Escape all double quotes (") in the "Vulnerable code snippets" to single quotes (').
                2. Don't leave empty lines between pieces of JSON information.
                3. Do not enclose the JSON bodies within square brackets ([]).

                Example of the expected JSON format: 

                {json_example}

                Here's the code to analyze:

                {content}
                """

                response = openai.Completion.create(
                    engine="gpt-3.5-turbo-instruct",
                    prompt=new_prompt,
                    max_tokens=2000,
                    temperature=0.5
                )

                print(response)

                reviews.append({
                    'file': file.path,
                    'review': response.choices[0].text.strip()
                })

            consolidated_report1 = "\n".join([review['review'] for review in reviews])

            consolidated_report = "[" + fix_json_commas(consolidated_report1) + "]"

            report = ScanReport(
                repository_name=repo_full_name,
                review=consolidated_report,
            )
            report.save()

            return JsonResponse({'reviews': reviews})

        except GithubException as ge:
            logger.error(f"A GitHub-related error occurred: {str(ge)}")
            return JsonResponse({'error': f'GitHub error: {str(ge)}'}, status=500)

        except openai.error.OpenAIError as oe:
            logger.error(f"An error occurred while communicating with the OpenAI API: {str(oe)}")
            return JsonResponse({'error': f'OpenAI error: {str(oe)}'}, status=500)

        except Exception as e:
            logger.error(f"An unexpected error occurred: {str(e)}")
            return JsonResponse({'error': f'An error occurred: {str(e)}'}, status=500)

    else:
        return JsonResponse({'error': 'Only POST requests are accepted.'}, status=400)    

def show_reports(request):
    reports = ScanReport.objects.all().order_by('-scanned_at')
    return render(request, 'codereview/reports.html', {'reports': reports})

def download_scan_report(request, report_id):
    try:
        scan_report = ScanReport.objects.filter(id=report_id).first()
        if not scan_report:
            raise Http404("ScanReport does not exist")

        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename="{scan_report.repository_name}_report.pdf"'

        pdf = generate_pdf(scan_report)
        response.write(pdf)

        return response

    except Exception as e:
        logger.error(f"An unexpected error occurred: {str(e)}")
        return JsonResponse({'error': f'An error occurred: {str(e)}'}, status=500)

codereview/templates/codereview/base_generic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Icons -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">

    <title>SCARF</title>
    <style>
        body {
            font-family: "Poppins", sans-serif;
        }

        #sidebar {
            min-height: 100vh;
        }

        #sidebar .nav-link {
            margin: 10px 15px;
            border-radius: 5px;
            color: #333;
        }

        #sidebar .nav-link:hover {
            background-color: #008cba;
            color: white;
        }

        .navbar-custom {
            background-color: #000;
        }

        .navbar-custom .navbar-brand,
        .navbar-custom .navbar-text {
            color: #ffffff;
        }

        .table td,
        .table th {
            vertical-align: middle;
        }

        .equal-column-table {
            table-layout: fixed;
            width: 100%;
        }

        .equal-column-table th,
        .equal-column-table td {
            width: 33.33%;
            text-align: center;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
        }

        .icon-spacing {
            margin-right: 5px;
        }

        .bold-number {
            font-weight: bold;
        }

        .narrow-column {
            width: 1%;  
            white-space: nowrap;  
            font-weight: bold;  
        }
        
    </style>
</head>

<body>

    <nav class="navbar navbar-custom navbar-expand-lg">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#sidebar"
                aria-controls="sidebar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="#">
                <i class="bi bi-qr-code-scan icon-spacing"></i>
                SCARF
            </a>
        </div>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <nav id="sidebar" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="position-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'codereview:fetch-repos' %}">
                                <span data-feather="home"></span>
                                Repositories
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'codereview:show-reports' %}">
                                <span data-feather="file"></span>
                                Reports
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                {% block content %}{% endblock %}
            </main>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
        feather.replace()
    </script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        function scanRepository(repoFullName) {
            var csrfToken = $("meta[name='csrf-token']").attr("content");

            $.ajax({
                headers: { "X-CSRFToken": csrfToken },
                url: '/scan_repository/',
                method: 'POST',
                data: {
                    'repo_full_name': repoFullName
                },
                success: function (response) {
                    alert("Finished Scan for " + repoFullName);
                },
                error: function (error) {
                    alert("Error starting scan.");
                }
            });
        }
    </script>

</body>

</html>

codereview/templates/codereview/reports.html
{% extends "codereview/base_generic.html" %}

{% block content %}
<div class="table-responsive">
    <table class="table table-striped table-sm equal-column-table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Repository Name</th>
                <th scope="col">Scanned At</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for report in reports %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ report.repository_name }}</td>
                <td>{{ report.scanned_at }}</td>
                <td>
                    <a href="{% url 'codereview:download_scan_report' report.id %}" class="btn btn-primary">Download Report</a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="5" class="text-center">No reports available</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div> 
{% endblock %}

codereview/templates/codereview/repos.html
{% extends "codereview/base_generic.html" %}

{% block content %}
<div class="table-responsive"> 
    <table class="table table-striped table-sm equal-column-table"> 
        <thead>
            <tr>
                <th>#</th>
                <th>Repository Name</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% if repositories %}
                {% for repo in repositories %}
                    <tr>
                        <td class="narrow-column">{{ forloop.counter }}</td>
                        <td>{{ repo.name }}</td>
                        <td>{{ repo.private|yesno:"Private,Public" }}</td>
                        <td>
                            <button onclick="scanRepository('{{ repo.full_name }}')" class="btn btn-primary">Scan</button>
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="4">No repositories available.</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}